# 02 — Data Quality & Cleaning Validation
## Hospital Readmission Risk Prediction System (DISCHARGE)
**Dataset:** UCI Diabetes 130-US Hospitals (1999–2008)  
**Roadmap Task:** `P2-03`  
**Purpose:** Pull `raw.diabetic_data` and `staging.encounters` from PostgreSQL, systematically assert each clinical cleaning rule (C1–C13), analyze row changes, and produce visual validation of the cleaned dataset.

In [1]:
import sys
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import sqlalchemy as sa

# Styling
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['font.size'] = 11

from readmission.config import (
    REPO_ROOT,
    EXCLUDED_DISCHARGE_DISPOSITION_IDS,
    DROPPED_COLUMNS,
    KEPT_MEDICATIONS,
)
from readmission.db import get_engine

engine = get_engine()
print(f"Connected to database engine: {engine.url.render_as_string(hide_password=True)}")

Connected to database engine: postgresql://neondb_owner:***@ep-green-tree-b58mq81z-pooler.c-7.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require


### 1. Extracting Raw and Staging Datasets from PostgreSQL
We pull both tables from the Neon database to compare shapes, column schemas, and row transformations.

In [2]:
with engine.connect() as conn:
    df_raw = pd.read_sql(sa.text("SELECT * FROM raw.diabetic_data"), conn)
    df_staging = pd.read_sql(sa.text("SELECT * FROM staging.encounters"), conn)

print(f"Raw dataset shape:     {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")
print(f"Staging dataset shape: {df_staging.shape[0]:,} rows × {df_staging.shape[1]} columns")
print(f"Total rows dropped:    {len(df_raw) - len(df_staging):,} ({(len(df_raw) - len(df_staging)) / len(df_raw) * 100:.2f}%)")

Raw dataset shape:     101,766 rows × 50 columns
Staging dataset shape: 99,340 rows × 50 columns
Total rows dropped:    2,426 (2.38%)


### 2. Rule C1 & C2: Missing Values & Question Mark ('?') Elimination
Rule C1 ensured raw data was loaded without truncation. Rule C2 asserts all `'?'` placeholders have been converted or imputed in staging.

In [3]:
staging_qmarks = {}
for col in df_staging.columns:
    if df_staging[col].dtype == object or str(df_staging[col].dtype) == "string":
        q_count = (df_staging[col].astype(str) == "?").sum()
        if q_count > 0:
            staging_qmarks[col] = q_count

assert len(staging_qmarks) == 0, f"Remaining '?' found in staging: {staging_qmarks}"
print("ASSERTION PASSED: Exactly 0 question marks ('?') remain across all staging columns!")

ASSERTION PASSED: Exactly 0 question marks ('?') remain across all staging columns!


### 3. Rule C3: Drop Unknown/Invalid Gender
Ensures biological sex is known ('Male' or 'Female') and drops the 3 corrupt/unknown records.

In [4]:
raw_invalid_gender = (df_raw["gender"] == "Unknown/Invalid").sum()
staging_invalid_gender = (~df_staging["gender"].isin(["Male", "Female"])).sum()

print(f"Raw encounters with invalid gender: {raw_invalid_gender}")
print(f"Staging encounters with invalid gender: {staging_invalid_gender}")
assert raw_invalid_gender == 3, f"Expected 3 invalid gender rows in raw, got {raw_invalid_gender}"
assert staging_invalid_gender == 0, "Staging contains invalid gender records!"
print("ASSERTION PASSED: Exactly 3 invalid gender records dropped.")

Raw encounters with invalid gender: 3
Staging encounters with invalid gender: 0
ASSERTION PASSED: Exactly 3 invalid gender records dropped.


### 4. Rule C4: Exclude Hospice & Expired Patients
Patients discharged to hospice or who expired during the stay cannot experience an unplanned 30-day readmission to an acute care hospital. Including them would introduce severe label bias and data leakage.

In [5]:
hospice_ids = set(EXCLUDED_DISCHARGE_DISPOSITION_IDS)
raw_hospice = df_raw["discharge_disposition_id"].astype(int).isin(hospice_ids).sum()
staging_hospice = df_staging["discharge_disposition_id"].isin(hospice_ids).sum()

print(f"Raw encounters with hospice/expired dispositions (11,13,14,19,20,21): {raw_hospice:,}")
print(f"Staging encounters with hospice/expired dispositions: {staging_hospice}")
assert raw_hospice == 2423, f"Expected 2423 hospice encounters in raw, found {raw_hospice}"
assert staging_hospice == 0, "Staging contains hospice/expired encounters!"
print("ASSERTION PASSED: Exactly 2,423 hospice/expired encounters excluded.")

Raw encounters with hospice/expired dispositions (11,13,14,19,20,21): 2,423
Staging encounters with hospice/expired dispositions: 0
ASSERTION PASSED: Exactly 2,423 hospice/expired encounters excluded.


### 5. Rule C5: Assert encounter_id Uniqueness
Verifies that the unit of observation is strictly one row per acute encounter.

In [6]:
raw_dupes = len(df_raw) - df_raw["encounter_id"].nunique()
staging_dupes = len(df_staging) - df_staging["encounter_id"].nunique()

assert raw_dupes == 0, f"Raw has {raw_dupes} duplicate encounter IDs"
assert staging_dupes == 0, f"Staging has {staging_dupes} duplicate encounter IDs"
print(f"ASSERTION PASSED: All {len(df_staging):,} encounters have unique encounter_id.")
print(f"Unique patients represented in staging: {df_staging['patient_nbr'].nunique():,}")

ASSERTION PASSED: All 99,340 encounters have unique encounter_id.
Unique patients represented in staging: 69,987


### 6. Rule C6 & C7: Imputation of Missing Demographics and Specialties
`race` missing values map to `'Unknown'`, while `medical_specialty` missing values map to `'Missing'`.

In [7]:
print("Race distribution in staging:")
print(df_staging["race"].value_counts())
assert (df_staging["race"] == "?").sum() == 0
assert df_staging["race"].isna().sum() == 0

print("\nTop 5 medical specialties in staging:")
print(df_staging["medical_specialty"].value_counts().head(5))
assert (df_staging["medical_specialty"] == "?").sum() == 0
assert df_staging["medical_specialty"].isna().sum() == 0
print("\nASSERTION PASSED: Demographics and specialties properly imputed with informative categories.")

Race distribution in staging:
race
Caucasian          74220
AfricanAmerican    18772
Unknown             2232
Hispanic            2017
Other               1471
Asian                628
Name: count, dtype: int64

Top 5 medical specialties in staging:
medical_specialty
Missing                   48614
InternalMedicine          14237
Emergency/Trauma           7419
Family/GeneralPractice     7252
Cardiology                 5278
Name: count, dtype: int64

ASSERTION PASSED: Demographics and specialties properly imputed with informative categories.


### 7. Rule C8: Lab Result Standardization
In clinical documentation, `'None'` in `A1Cresult` and `max_glu_serum` indicates that the physician did not order the test during the encounter. It is an informative category, not missing data. Both `'None'` and `'?'` are standardized to `'NotMeasured'`.

In [8]:
print("A1Cresult distribution in staging:")
print(df_staging["a1c_result"].value_counts())
print("\nmax_glu_serum distribution in staging:")
print(df_staging["max_glu_serum"].value_counts())

assert "None" not in df_staging["a1c_result"].values
assert "?" not in df_staging["a1c_result"].values
assert "None" not in df_staging["max_glu_serum"].values
assert "?" not in df_staging["max_glu_serum"].values
print("\nASSERTION PASSED: Lab results standardized with 'NotMeasured'.")

A1Cresult distribution in staging:
a1c_result
NotMeasured    82506
>8              8137
Norm            4922
>7              3775
Name: count, dtype: int64

max_glu_serum distribution in staging:
max_glu_serum
NotMeasured    94188
Norm            2545
>200            1419
>300            1188
Name: count, dtype: int64

ASSERTION PASSED: Lab results standardized with 'NotMeasured'.


### 8. Rule C9 & C10: Verification of Dropped Sparse and Zero-Variance Columns
Columns dropped:
- `weight` (96.86% missing)
- `payer_code` (39.56% missing billing data)
- `examide` (constant 'No')
- `citoglipton` (constant 'No')

In [9]:
for dropped_col in DROPPED_COLUMNS:
    assert dropped_col not in df_staging.columns, f"Column {dropped_col} should have been dropped!"
print(f"ASSERTION PASSED: Dropped columns {DROPPED_COLUMNS} successfully excluded from staging.")

ASSERTION PASSED: Dropped columns ['weight', 'payer_code', 'examide', 'citoglipton'] successfully excluded from staging.


### 9. Rule C11: Numeric Ranges & Types
Validates that lengths of stay fall between 1 and 14 days, and all procedure, medication, and historical visit counts are non-negative integers.

In [10]:
numeric_checks = [
    ("time_in_hospital", 1, 14),
    ("num_lab_procedures", 0, 200),
    ("num_procedures", 0, 10),
    ("num_medications", 0, 150),
    ("number_outpatient", 0, 100),
    ("number_emergency", 0, 100),
    ("number_inpatient", 0, 50),
    ("number_diagnoses", 0, 20),
]

for col, min_val, max_val in numeric_checks:
    actual_min = df_staging[col].min()
    actual_max = df_staging[col].max()
    assert actual_min >= min_val and actual_max <= max_val, f"{col} out of bounds: [{actual_min}, {actual_max}]"
    print(f"✔ {col}: range [{actual_min}, {actual_max}] (type: {df_staging[col].dtype})")
print("\nASSERTION PASSED: All numeric features satisfy clinical bounds and integer types.")

✔ time_in_hospital: range [1, 14] (type: int64)
✔ num_lab_procedures: range [1, 132] (type: int64)
✔ num_procedures: range [0, 6] (type: int64)
✔ num_medications: range [1, 81] (type: int64)
✔ number_outpatient: range [0, 42] (type: int64)
✔ number_emergency: range [0, 76] (type: int64)
✔ number_inpatient: range [0, 21] (type: int64)
✔ number_diagnoses: range [1, 16] (type: int64)

ASSERTION PASSED: All numeric features satisfy clinical bounds and integer types.


### 10. Rule C13: Dimension Table Descriptions
Checks that foreign keys for admission type, discharge disposition, and admission source were mapped to descriptive labels from `staging.dim_*`.

In [11]:
print("Top 5 Discharge Dispositions:")
print(df_staging["discharge_disposition_desc"].value_counts().head(5))

print("\nTop 5 Admission Sources:")
print(df_staging["admission_source_desc"].value_counts().head(5))

assert df_staging["admission_type_desc"].isna().sum() == 0
assert df_staging["discharge_disposition_desc"].isna().sum() == 0
assert df_staging["admission_source_desc"].isna().sum() == 0
print("\nASSERTION PASSED: Dimension descriptions joined successfully.")

Top 5 Discharge Dispositions:
discharge_disposition_desc
Discharged to home                                         60232
Discharged/transferred to SNF                              13954
Discharged/transferred to home with home health service    12902
NULL                                                        3691
Discharged/transferred to another short term hospital       2128
Name: count, dtype: int64

Top 5 Admission Sources:
admission_source_desc
Emergency Room                                55848
Physician Referral                            29167
NULL                                           6570
Transfer from a hospital                       3118
Transfer from another health care facility     2239
Name: count, dtype: int64

ASSERTION PASSED: Dimension descriptions joined successfully.


### 11. Target Variable Distribution & Imbalance
The target `readmitted_30d` is defined as 1 if the patient had an unplanned readmission in under 30 days (`readmitted == '<30'`), and 0 otherwise.

In [12]:
target_counts = df_staging["readmitted_30d"].value_counts()
target_pcts = df_staging["readmitted_30d"].value_counts(normalize=True) * 100

summary_df = pd.DataFrame({
    "Count": target_counts,
    "Percentage (%)": target_pcts.round(2)
})
summary_df.index = ["Negative (No readmission <30d)", "Positive (Readmitted <30d)"]
print(summary_df)

fig, ax = plt.subplots(figsize=(7, 4))
bars = ax.bar(["Negative (0)", "Positive (1)"], target_counts.values, color=["#3b82f6", "#ef4444"], width=0.5)
ax.set_ylabel("Encounters")
ax.set_title(f"Target Distribution (readmitted_30d) — Base Rate: {target_pcts[1]:.2f}%")
for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, yval + 1000, f"{yval:,} ({yval/len(df_staging)*100:.1f}%)", ha='center', va='bottom')
plt.tight_layout()
fig_path = REPO_ROOT / "reports" / "figures" / "staging_target_distribution.png"
fig_path.parent.mkdir(parents=True, exist_ok=True)
plt.savefig(fig_path, dpi=150)
plt.close()

                                Count  Percentage (%)
Negative (No readmission <30d)  88026           88.61
Positive (Readmitted <30d)      11314           11.39


### 12. Rule-by-Rule Impact Summary
Table and horizontal bar chart visualizing the row progression from raw (101,766) to clean staging (99,340).

In [13]:
progression = [
    ("Raw CSV Ingested", 101766, 0),
    ("Rule C3: Invalid Gender", 101763, -3),
    ("Rule C4: Expired/Hospice", 99340, -2423),
]

prog_df = pd.DataFrame(progression, columns=["Cleaning Step", "Remaining Rows", "Rows Dropped"])
print(prog_df.to_string(index=False))

fig, ax = plt.subplots(figsize=(8, 4))
ax.barh(prog_df["Cleaning Step"], prog_df["Remaining Rows"], color="#10b981", height=0.4)
ax.set_xlim(95000, 103000)
ax.set_xlabel("Encounters Remaining")
ax.set_title("Dataset Cleaning Progression (C1–C13)")
for i, v in enumerate(prog_df["Remaining Rows"]):
    ax.text(v + 200, i, f"{v:,}", va='center', fontweight='bold')
plt.tight_layout()
fig_prog_path = REPO_ROOT / "reports" / "figures" / "cleaning_progression.png"
plt.savefig(fig_prog_path, dpi=150)
plt.close()
print("\nPhase 2 cleaning validation completed successfully!")

           Cleaning Step  Remaining Rows  Rows Dropped
        Raw CSV Ingested          101766             0
 Rule C3: Invalid Gender          101763            -3
Rule C4: Expired/Hospice           99340         -2423

Phase 2 cleaning validation completed successfully!
